<?php

namespace Tests\Unit\Observers;

use App\Models\Registration;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

/**
 * Unit tests for RegistrationObserver
 *
 * Tests cover:
 * - QR code auto-generation when registration is validated
 * - QR code generation on create vs update
 * - QR code deletion when registration is deleted
 * - No QR code generated for non-validated registrations
 */
class RegistrationObserverTest extends TestCase
{
    use RefreshDatabase;

    /**
     * Setup test environment before each test
     */
    protected function setUp(): void
    {
        parent::setUp();

        Storage::fake('public');
    }

    /**
     * Test QR code is generated when registration is created as validated
     */
    public function test_qr_code_generated_when_registration_created_validated(): void
    {
        $registration = Registration::factory()->validated()->create();

        // Observer should have been triggered by create() and QR code generated
        $registration->refresh();

        // Check QR code was generated
        $this->assertNotNull($registration->qr_code_path);
        $this->assertStringContainsString('qrcodes/', $registration->qr_code_path);
        Storage::disk('public')->assertExists($registration->qr_code_path);
    }

    /**
     * Test QR code is NOT generated when registration is created as non-validated
     */
    public function test_no_qr_code_when_registration_created_not_validated(): void
    {
        $registration = Registration::factory()->create();

        $registration->refresh();

        // Check QR code was NOT generated
        $this->assertNull($registration->qr_code_path);
    }

    /**
     * Test QR code is generated when registration is updated to validated
     */
    public function test_qr_code_generated_when_registration_updated_to_validated(): void
    {
        $registration = Registration::factory()->create(['reg_validated' => false]);
        $this->assertNull($registration->qr_code_path);

        // Update to validated (this triggers the observer automatically)
        $registration->reg_validated = true;
        $registration->save();

        // Observer should have generated QR code
        $registration->refresh();

        $this->assertNotNull($registration->qr_code_path);
        Storage::disk('public')->assertExists($registration->qr_code_path);
    }

    /**
     * Test QR code is deleted when registration is deleted
     */
    public function test_qr_code_deleted_when_registration_deleted(): void
    {
        $registration = Registration::factory()->validated()->create();

        // Registration should have QR code generated by observer
        $registration->refresh();
        $qrPath = $registration->qr_code_path;

        $this->assertNotNull($qrPath);
        Storage::disk('public')->assertExists($qrPath);

        // Delete registration (triggers observer)
        $registration->delete();

        // QR code should be deleted
        Storage::disk('public')->assertMissing($qrPath);
    }

    /**
     * Test no duplicate QR code generation if already exists
     */
    public function test_no_duplicate_qr_code_if_already_exists(): void
    {
        $existingPath = 'qrcodes/existing_qr.svg';
        $registration = Registration::factory()->create(['reg_validated' => true, 'qr_code_path' => $existingPath]);

        // Path should remain unchanged (not regenerated)
        $this->assertEquals($existingPath, $registration->qr_code_path);
    }

    /**
     * Test QR code service generates valid path format
     */
    public function test_qr_code_path_format(): void
    {
        $registration = Registration::factory()->validated()->create();

        $registration->refresh();

        // Check path format
        $expectedPattern = sprintf(
            'qrcodes/team_%d_reg_%d.svg',
            $registration->equ_id,
            $registration->reg_id
        );
        $this->assertEquals($expectedPattern, $registration->qr_code_path);
    }
}
